In [1]:
import pandas as pd
import sqlite3

# Load cleaned dataset
df = pd.read_csv(r"D:\UAE-Telecom-Churn-Analytics\data\processed\cleaned_uae_telecom_data.csv")

# Create database
conn = sqlite3.connect(r"D:\UAE-Telecom-Churn-Analytics\sql\uae_telecom.db")

# Export dataframe to SQL table
df.to_sql('telecom_customers', conn, if_exists='replace', index=False)

print("Database created successfully")

Database created successfully

In [2]:
import sqlite3

conn = sqlite3.connect(
    r"D:\UAE-Telecom-Churn-Analytics\sql\uae_telecom.db"
)

print("Connected Successfully!")

Connected Successfully!

In [3]:
query = """
SELECT *
FROM telecom_customers
LIMIT 5;
"""

result = pd.read_sql(query, conn)

result

,CustomerID,Age,Gender,Tenure,MonthlyCharges,Contract,PaymentMethod,TotalCharges,Churn,Emirate,Nationality_Group,5G_Subscription,Premium_Customer_Tier,International_Roaming_Usage_GB,Ramadan_Usage_Spike_Percentage,WhatsApp_Call_Dependency,Estimated_ARPU_AED,Likely_Churn_Reason
0,1,56,Female,68,147.58,Two year,Bank transfer,10052.03,No,Dubai,Filipino Expat,Yes,Silver,1.57,10.5,Low,205.07,Better 5G Plans Available
1,2,69,Male,32,22.54,Month-to-month,Mailed check,686.78,No,Fujairah,Pakistani Expat,Yes,Standard,4.72,14.9,High,29.58,Competitor Offer
2,3,46,Female,10,52.47,One year,Electronic check,537.88,No,Sharjah,Indian Expat,Yes,Silver,5.42,13.6,Low,62.82,Better 5G Plans Available
3,4,32,Male,22,109.67,Month-to-month,Mailed check,2390.04,Yes,Abu Dhabi,Pakistani Expat,Yes,Gold,12.86,6.3,Low,138.45,Poor International Roaming
4,5,60,Female,54,130.98,Month-to-month,Credit card,7081.28,No,Dubai,Indian Expat,Yes,Gold,12.85,12.4,High,188.93,Competitor Offer

In [4]:
query = """
SELECT COUNT(*) AS total_customers
FROM telecom_customers;
"""

result = pd.read_sql(query, conn)

result

   total_customers
0           100000

In [5]:
query = """
SELECT Churn,
       COUNT(*) AS customer_count
FROM telecom_customers
GROUP BY Churn;
"""

result = pd.read_sql(query, conn)

result

  Churn  customer_count
0    No           66856
1   Yes           33144

In [6]:
query = """
SELECT Churn,
       ROUND(
           COUNT(*) * 100.0 /
           (SELECT COUNT(*) FROM telecom_customers),
           2
       ) AS churn_percentage
FROM telecom_customers
GROUP BY Churn;
"""

result = pd.read_sql(query, conn)

result

  Churn  churn_percentage
0    No             66.86
1   Yes             33.14

In [7]:
query = """
SELECT Emirate,
       COUNT(*) AS total_customers
FROM telecom_customers
GROUP BY Emirate
ORDER BY total_customers DESC;
"""

result = pd.read_sql(query, conn)

result

          Emirate  total_customers
0           Dubai            38039
1       Abu Dhabi            26999
2         Sharjah            15057
3           Ajman             7061
4  Ras Al Khaimah             5980
5        Fujairah             3969
6   Umm Al Quwain             2895

In [8]:
query = """
SELECT CustomerID,
       MonthlyCharges,
       Premium_Customer_Tier
FROM telecom_customers
ORDER BY MonthlyCharges DESC
LIMIT 10;
"""

result = pd.read_sql(query, conn)

result

   CustomerID  MonthlyCharges Premium_Customer_Tier
0       47795          150.00              Standard
1       54259          150.00              Platinum
2       60120          150.00                Silver
3       66531          150.00              Standard
4       70893          150.00                Silver
5       15279          149.99              Platinum
6       63438          149.99                  Gold
7       73731          149.99              Standard
8       28553          149.98              Platinum
9       38327          149.98              Platinum

In [9]:
query = """
SELECT "5G_Subscription",
       COUNT(*) AS total_customers
FROM telecom_customers
GROUP BY "5G_Subscription";
"""

result = pd.read_sql(query, conn)

result

  5G_Subscription  total_customers
0              No            45115
1             Yes            54885

In [10]:
query = """
SELECT Premium_Customer_Tier,
       COUNT(*) AS customer_count
FROM telecom_customers
GROUP BY Premium_Customer_Tier;
"""

result = pd.read_sql(query, conn)

result

  Premium_Customer_Tier  customer_count
0                  Gold            9615
1              Platinum            5114
2                Silver           25537
3              Standard           59734

In [11]:
query = """
SELECT ROUND(AVG(MonthlyCharges),2)
AS average_monthly_revenue
FROM telecom_customers;
"""

result = pd.read_sql(query, conn)

result

   average_monthly_revenue
0                    79.97

In [12]:
query = """
SELECT Emirate,
       Churn,
       COUNT(*) AS customer_count
FROM telecom_customers
GROUP BY Emirate, Churn
ORDER BY Emirate;
"""

result = pd.read_sql(query, conn)

result

           Emirate Churn  customer_count
0        Abu Dhabi    No           18125
1        Abu Dhabi   Yes            8874
2            Ajman    No            4674
3            Ajman   Yes            2387
4            Dubai    No           25379
5            Dubai   Yes           12660
6         Fujairah    No            2697
7         Fujairah   Yes            1272
8   Ras Al Khaimah    No            3950
9   Ras Al Khaimah   Yes            2030
10         Sharjah    No           10150
11         Sharjah   Yes            4907
12   Umm Al Quwain    No            1881
13   Umm Al Quwain   Yes            1014